### ISSUE TITLE
Confusing of the occlusion map

### ISSUE THREAD

**Issue by lelelexxx** [anuragranj/back2future.pytorch#1]
Thanks for your sharing~!

After read your paper, I noticed that, the occlusion estimation of your work is mapped to (0,1), and the occlusion estimation is used as the weight of photometric loss.
While in your paper, the occlusion estimation in Fig.3 is something like a binary map, and in the last of second paragraph of section 4.2, you said 'This clearly shows the benefit of ignoring misleading information in accordance with the occlusion estimates'. It is a little confusing to me. Is the occlusion estimation transformed into binary map? Or you just transform occlusion maps for visualizing?  

Any reply will be appreciated~
Thanks again.

**Comment by anuragranj** [comment]
The predicted occlusions from the network are indeed real numbers between 0 and 1. We threshold them for visualization.
