### ISSUE TITLE
Non-shared weights for network branches?

### ISSUE THREAD

**Issue by InnovArul** [anuragranj/back2future.pytorch#6]
Hi,

thanks for sharing the code.
I have a generic question w.r.t the model's code.
I see that you have used three (non-shared weights) branches for 3 images in the lines: 
https://github.com/anuragranj/back2future.pytorch/blob/master/back2future.py#L147-L166

In your experience, do you suggest having non-shared weights for image encoding? 
I have noticed that PWCNet has shared weights for these branches.

I understand you did not train with pytorch. So, I am not sure if you have shared weights when you trained with Lua torch.

**Comment by anuragranj** [comment]
PWC also has non-shared weights, at least in the official implementation. https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/models/PWCNet.py

**Comment by InnovArul** [comment]
Thanks for your reply!
I referred to the code from NVIDIA as well.
From these lines:  https://github.com/NVlabs/PWC-Net/blob/185b0e2beb45ad029bb66d818812f8dcc2aed9c6/PyTorch/models/PWCNet.py#L182-L193

```python
def forward(self, im1, im2):
        ...
        c11 = self.conv1b(self.conv1aa(self.conv1a(im1)))
        c21 = self.conv1b(self.conv1aa(self.conv1a(im2)))
        c12 = self.conv2b(self.conv2aa(self.conv2a(c11)))
        c22 = self.conv2b(self.conv2aa(self.conv2a(c21)))
        c13 = self.conv3b(self.conv3aa(self.conv3a(c12)))
        c23 = self.conv3b(self.conv3aa(self.conv3a(c22)))
        c14 = self.conv4b(self.conv4aa(self.conv4a(c13)))
        c24 = self.conv4b(self.conv4aa(self.conv4a(c23)))
        c15 = self.conv5b(self.conv5aa(self.conv5a(c14)))
        c25 = self.conv5b(self.conv5aa(self.conv5a(c24)))
        c16 = self.conv6b(self.conv6a(self.conv6aa(c15)))
        c26 = self.conv6b(self.conv6a(self.conv6aa(c25)))
        ...
```
, I am seeing that they are sharing weights between the two branches of the network. 
Did I miss anything?

**Comment by anuragranj** [comment]
Oh yes. You are right. I am not sure if sharing is better or worse. I am not aware of any study around it.

**Comment by InnovArul** [comment]
Cool! thanks for your reply.

**Comment by JJanai** [comment]
Just for completeness. During training we also shared the weights (see lua code) and I think this is important for learning good features for the matching problem. Since this code was only provided for inference, this should not have any effect but your feedback is helpful for people who wants to train a model based on this code. Thanks for pointing it out.

**Comment by InnovArul** [comment]
That makes sense. Thanks for clarifying this.
